/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clock;
import java.util.TimeZone;
import javax.swing.*;
import java.awt.*;
import java.net.URL;

/**
 *
 * @author 226797
 */
public class NumClock extends javax.swing.JFrame {
    private String year;
    private String month;
    private String day;
    private String hour;
    private String minute;
    private String second;
    private SelectTimeZone nstz;
    String week ;
    /**
     * Creates new form NumClock
     */
    public void SetTime() {
        JTextYear.setText(year);
        JTextYear.setFont(new Font(JTextYear.getFont().getName(),JTextYear.getFont().getStyle(),15));
        JTextMonth.setText(month);
        JTextMonth.setFont(new Font(JTextMonth.getFont().getName(),JTextMonth.getFont().getStyle(),15));
        JTextDay.setText(day);
        JTextDay.setFont(new Font(JTextDay.getFont().getName(),JTextDay.getFont().getStyle(),15));
        JTextHour.setText(hour);
        JTextHour.setFont(new Font(JTextHour.getFont().getName(),JTextHour.getFont().getStyle(),25));
        JTextMinute.setText(minute);
        JTextMinute.setFont(new Font(JTextMinute.getFont().getName(),JTextMinute.getFont().getStyle(),25));
        JTextSecond.setText(second);
        JTextSecond.setFont(new Font(JTextSecond.getFont().getName(),JTextSecond.getFont().getStyle(),25));
        jLabel1.setText(week);
    }
    public void SendTime(int y, int m, int d, int h, int minutes, int s, String t, String x) {
        //该函数使用线程Thread，放在构造函数中
        year = String.valueOf(y);
        month = String.valueOf(m);
        day = String.valueOf(d);
        hour = String.valueOf(h);
        minute = String.valueOf(minutes);
        second = String.valueOf(s);
        week = x;
        SetTime();
    }
    
    
    public NumClock() {
        initComponents();
        nstz = new SelectTimeZone();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextHour = new javax.swing.JLabel();
        JTextMinute = new javax.swing.JLabel();
        JTextSecond = new javax.swing.JLabel();
        JTextYear = new javax.swing.JLabel();
        JTextMonth = new javax.swing.JLabel();
        JTextDay = new javax.swing.JLabel();
        CountDown = new javax.swing.JButton();
        add = new javax.swing.JButton();
        alarm = new javax.swing.JButton();
        ChangeTimeZone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTextHour.setText("jLabel1");

        JTextMinute.setText("jLabel2");

        JTextSecond.setText("jLabel4");

        JTextYear.setText("jLabel1");

        JTextMonth.setText("jLabel1");

        JTextDay.setText("jLabel1");

        CountDown.setText("倒计时");
        CountDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountDownActionPerformed(evt);
            }
        });

        add.setText("添加");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        alarm.setText("闹钟");
        alarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmActionPerformed(evt);
            }
        });

        ChangeTimeZone.setText("更换时区");
        ChangeTimeZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeTimeZoneActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ChangeTimeZone)
                        .addGap(18, 18, 18)
                        .addComponent(alarm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CountDown, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextDay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(JTextHour, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTextSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextHour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTextYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextDay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountDown)
                    .addComponent(add)
                    .addComponent(alarm)
                    .addComponent(ChangeTimeZone))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public TimeZone getZone()
    {
        return nstz.getNewZone();
    }
    private void CountDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountDownActionPerformed
                // TODO add your handling code here:
        CoundownPage nw = new CoundownPage();
        nw.setVisible(true);
    }//GEN-LAST:event_CountDownActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         AlarmUI a1 =new  AlarmUI();
         a1.setVisible(true);
  
    }//GEN-LAST:event_addActionPerformed

    private void alarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmActionPerformed
        // TODO add your handling code here:
        new reminderAlarm();
    }//GEN-LAST:event_alarmActionPerformed

    private void ChangeTimeZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeTimeZoneActionPerformed
        // TODO add your handling code here:
        nstz.setVisible(true);
    }//GEN-LAST:event_ChangeTimeZoneActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NumClock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeTimeZone;
    private javax.swing.JButton CountDown;
    private javax.swing.JLabel JTextDay;
    private javax.swing.JLabel JTextHour;
    private javax.swing.JLabel JTextMinute;
    private javax.swing.JLabel JTextMonth;
    private javax.swing.JLabel JTextSecond;
    private javax.swing.JLabel JTextYear;
    private javax.swing.JButton add;
    private javax.swing.JButton alarm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
