package com.mycompany.clock;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 薛梓屹
 */
import java.util.TimeZone;
public class SelectTimeZone extends javax.swing.JFrame{

    /**
     * Creates new form SelectTimeZone
     */
    public SelectTimeZone() {
        initComponents();
        buttonGroup1.add(RadioButtonChina);
        buttonGroup1.add(RadioButtonJapan);
        buttonGroup1.add(RadioButtonUS);
        buttonGroup1.add(RadioButtonUK);
        buttonGroup1.add(RadioButtonRussia);
        buttonGroup1.add(RadioButtonCanada);
        buttonGroup1.add(RadioButtonAustralia);
        buttonGroup1.add(RadioButtonNewZealand);
        RadioButtonChina.setSelected(true);
        tz = TimeZone.getTimeZone("GMT+8:00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TimeZoneLabel = new javax.swing.JLabel();
        RadioButtonChina = new javax.swing.JRadioButton();
        RadioButtonJapan = new javax.swing.JRadioButton();
        RadioButtonUS = new javax.swing.JRadioButton();
        RadioButtonUK = new javax.swing.JRadioButton();
        RadioButtonRussia = new javax.swing.JRadioButton();
        RadioButtonCanada = new javax.swing.JRadioButton();
        RadioButtonAustralia = new javax.swing.JRadioButton();
        RadioButtonNewZealand = new javax.swing.JRadioButton();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TimeZoneLabel.setText("请选择所在时区：");

        RadioButtonChina.setText("中国");
        RadioButtonChina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonChinaActionPerformed(evt);
            }
        });

        RadioButtonJapan.setText("日本");
        RadioButtonJapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonJapanActionPerformed(evt);
            }
        });

        RadioButtonUS.setText("美国");
        RadioButtonUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonUSActionPerformed(evt);
            }
        });

        RadioButtonUK.setText("英国");
        RadioButtonUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonUKActionPerformed(evt);
            }
        });

        RadioButtonRussia.setText("俄罗斯");
        RadioButtonRussia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonRussiaActionPerformed(evt);
            }
        });

        RadioButtonCanada.setText("加拿大");
        RadioButtonCanada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonCanadaActionPerformed(evt);
            }
        });

        RadioButtonAustralia.setText("澳大利亚");
        RadioButtonAustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonAustraliaActionPerformed(evt);
            }
        });

        RadioButtonNewZealand.setText("新西兰");
        RadioButtonNewZealand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonNewZealandActionPerformed(evt);
            }
        });

        OKButton.setText("确定");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("切换回中国时区");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeZoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonJapan)
                    .addComponent(RadioButtonUS)
                    .addComponent(RadioButtonUK)
                    .addComponent(RadioButtonRussia)
                    .addComponent(RadioButtonCanada)
                    .addComponent(RadioButtonAustralia)
                    .addComponent(RadioButtonNewZealand)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RadioButtonChina, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeZoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonChina, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonJapan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonUS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonUK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonRussia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonCanada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonNewZealand, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(OKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonChinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonChinaActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+8:00");
    }//GEN-LAST:event_RadioButtonChinaActionPerformed

    private void RadioButtonJapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonJapanActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+9:00");
    }//GEN-LAST:event_RadioButtonJapanActionPerformed

    private void RadioButtonCanadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonCanadaActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT-5:00");
    }//GEN-LAST:event_RadioButtonCanadaActionPerformed

    private void RadioButtonUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonUSActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT-5:00");
    }//GEN-LAST:event_RadioButtonUSActionPerformed

    private void RadioButtonUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonUKActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+0:00");
    }//GEN-LAST:event_RadioButtonUKActionPerformed

    private void RadioButtonRussiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonRussiaActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+3:00");
    }//GEN-LAST:event_RadioButtonRussiaActionPerformed

    private void RadioButtonAustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonAustraliaActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+11:00");
    }//GEN-LAST:event_RadioButtonAustraliaActionPerformed

    private void RadioButtonNewZealandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonNewZealandActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+13:00");
    }//GEN-LAST:event_RadioButtonNewZealandActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        tz = TimeZone.getTimeZone("GMT+8:00");
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed
    TimeZone getNewZone()
    {
        return tz;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTimeZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTimeZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTimeZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTimeZone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTimeZone().setVisible(true);
            }
        });
    }
    private TimeZone tz;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JRadioButton RadioButtonAustralia;
    private javax.swing.JRadioButton RadioButtonCanada;
    private javax.swing.JRadioButton RadioButtonChina;
    private javax.swing.JRadioButton RadioButtonJapan;
    private javax.swing.JRadioButton RadioButtonNewZealand;
    private javax.swing.JRadioButton RadioButtonRussia;
    private javax.swing.JRadioButton RadioButtonUK;
    private javax.swing.JRadioButton RadioButtonUS;
    private javax.swing.JLabel TimeZoneLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
